### PR TITLE
Fix float conversion overflow problems

### LINKED ISSUE #10: Truncation result can change based upon precision specified
@TotalVerb the changes you did in 7623549 seemed to have undone some of the changes in d7c2d5c.

```julia
import FixedPointDecimals: FD
for i in 0:18
    println(lpad(i, 2), " ", repr(trunc(FD{Int,i}, 2.3)))
end
```

On revision d7c2d5c we get:
```
 0 FixedDecimal{Int64,0}(2)
 1 FixedDecimal{Int64,1}(2.2)
 2 FixedDecimal{Int64,2}(2.29)
 3 FixedDecimal{Int64,3}(2.299)
 4 FixedDecimal{Int64,4}(2.2999)
 5 FixedDecimal{Int64,5}(2.29999)
 6 FixedDecimal{Int64,6}(2.299999)
 7 FixedDecimal{Int64,7}(2.2999999)
 8 FixedDecimal{Int64,8}(2.29999999)
 9 FixedDecimal{Int64,9}(2.299999999)
10 FixedDecimal{Int64,10}(2.2999999999)
11 FixedDecimal{Int64,11}(2.29999999999)
12 FixedDecimal{Int64,12}(2.299999999999)
13 FixedDecimal{Int64,13}(2.2999999999999)
14 FixedDecimal{Int64,14}(2.29999999999999)
15 FixedDecimal{Int64,15}(2.299999999999999)
16 FixedDecimal{Int64,16}(2.2999999999999998)
17 FixedDecimal{Int64,17}(2.29999999999999984)
18 FixedDecimal{Int64,18}(2.299999999999999808)
```

While on revision 7623549:
```
 0 FixedDecimal{Int64,0}(2)
 1 FixedDecimal{Int64,1}(2.2)
 2 FixedDecimal{Int64,2}(2.29)
 3 FixedDecimal{Int64,3}(2.299)
 4 FixedDecimal{Int64,4}(2.2999)
 5 FixedDecimal{Int64,5}(2.29999)
 6 FixedDecimal{Int64,6}(2.299999)
 7 FixedDecimal{Int64,7}(2.2999999)
 8 FixedDecimal{Int64,8}(2.29999999)
 9 FixedDecimal{Int64,9}(2.299999999)
10 FixedDecimal{Int64,10}(2.2999999999)
11 FixedDecimal{Int64,11}(2.29999999999)
12 FixedDecimal{Int64,12}(2.299999999999)
13 FixedDecimal{Int64,13}(2.2999999999999)
14 FixedDecimal{Int64,14}(2.29999999999999)
15 FixedDecimal{Int64,15}(2.299999999999999)
16 FixedDecimal{Int64,16}(2.3000000000000000)  # The issue
17 FixedDecimal{Int64,17}(2.29999999999999968)
18 FixedDecimal{Int64,18}(2.299999999999999744)
```

### PR DESCRIPTION
**Pull request by TotalVerb**
Fix #10.

There are two problems fixed here:

- change truncmul and friends to take a type as first argument. this can be the integer type, avoiding a floating point precision loss with `+`.
- if 10^n is not exactly representable as a float, promote to a sufficiently sized BigFloat while performing the computation

The existing tests have been bumped from 12 to 18, and I added a new test that goes to 200 with BigInt.

### CODE REVIEW

File: test/runtests.jl [hunk 1]
```diff
@@ -50,6 +50,9 @@ const INTS = Dict(
     2.2  => "220000000000000017763568394002504646778106689453125",
     2.3  => "229999999999999982236431605997495353221893310546875"
 )
+for (k, v) in INTS
+    INTS[k] = rpad(v, 201, "0")
+end
```
Comment (omus) [inline test/runtests.jl]: Lets just switch to generating these numbers at this point:
```julia
const INTS = Dict(
    v => replace(@sprintf("%.200f", v), ".", "")
    for v in [
        1.22,
        1.23,
        1.51,
        2.2,
        2.3,
    ]
)
```

Comment (omus) [inline test/runtests.jl]: I added this in

**Comment by omus** [comment]
I resolve the conflicts for you. We may want to do some performance benchmarks

**Comment by omus** [comment]
Some of the tests I added in https://github.com/JuliaMath/FixedPointDecimals.jl/pull/8 aren't playing nice with these changes. I'm attempting to modify the tests.

**Comment by omus** [comment]
I revised the tests around trunc, floor, and ceil to work with the improved precision. In order to test these functions properly I made the trunc_alt, floor_alt, and ceil_alt functions which perform their various operations using a string internally. Although inefficient these methods should allow us to verify that the mathematical calculations are precise.

Additionally, I found a bug in floormul and truncmul when `I <: Unsigned`.

**Comment by omus** [comment]
Ran into a strange problem with conditionally creating a function within a testset on Linux and Mac. Not quite sure how I'll get Appveyor to work yet.

**Comment by omus** [comment]
I believe I fixed Appveyor. My commit message should read "Switch to using `@sprintf` for Windows support". I'll fix that in a future rebase.

**Comment by TotalVerb** [comment]
Should we merge this now?

**Comment by omus** [comment]
I'll fix the commit history then merge it.
